version: '3'
services:
  app:
    container_name: api
    build: .
    ports:
      - 8000:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres-db
    networks:
      - my_network


  postgres-db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5436:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-db
    ports:
      - "5050:80"
    networks:
      - my_network
    restart: unless-stopped
volumes:
  api:
  database_postgres:
networks:
  my_network:
    driver: bridge