version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=mysecret
    ports:
    - 5436:5432
  api:
    depends_on:
      - postgres
    command: sh -c './wait-for host:5436 -- cmd'
    build: ./
    ports:
    - 8537:8653
